name: Auto Android

on:
  workflow_dispatch:
    inputs:
      format_java:
        default: false
        required: false
        type: boolean
      format_cpp:
        default: false
        required: false
        type: boolean
      job_type:
        default: 'build'
        required: false
        options:
          - build
          - check
          - test
        type: choice

jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Setup JDK 11
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Java Format
      if:  ${{ inputs.format_java }}
      uses: axel-op/googlejavaformat-action@v3.6.0
      with:
        files: "android/src/**/*.java"
        args: "-r -a"
    - name: Global Cpp Format
      if:  ${{ inputs.format_cpp }}
    - run: |
        git config --global user.email "ikomangwidiadaariasa12@gmail.com"
        git config --global user.name "AriasaProp"
        sudo apt-get install -y clang-format
        find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format -i
        git add .
        git commit -m "reformating cpp"
        git push
    - name: Gradle ${{ inputs.job_type }}
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.1.1
        arguments: ":android:${{ inputs.job_type }}"
    - name: Publish Artifacts
      if:  ${{ inputs.job_type == 'build' }}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: buildAPK
        path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk
