name: Auto Android

on:
  push:
    paths:
      - 'android/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Setup JDK 11
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.1.1
    - name: Gradle test
      run: gradle :android:test
    - name: Publish Test
      uses: actions/upload-artifact@v3.1.2
      with:
        name: report
        path: ${{ github.workspace }}/android/test
    - name: Gradle build
      run: gradle :android:build
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: buildAPK
        path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk
