name: Clean-Up Workflow

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          retain_days: 0
          keep_minimum_runs: 1
      - uses: glassechidna/artifact-cleaner@v2
        with:
          minimumAge: 360
