name: 'Cleanup Workflows'

on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3.5.2
      - run: |
          OT=$(gh api repos/:owner/:repo/actions/runs --jq '.workflow_runs[] | .id')
          IFS=$'\n'
          for run_id in $OT; do
            gh api repos/:owner/:repo/actions/runs/$run_id --method DELETE
          done
